import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from config import (
    SMTP_SERVER,
    SMTP_PORT,
    SMTP_USERNAME,
    SMTP_PASSWORD,
    ALERT_FROM,
    ALERT_TO,
    DEMO_MODE,
)

def send_alert_if_needed(scan_result: dict):
    findings = scan_result.get("findings", [])
    high_crit = [f for f in findings if f["severity"] in ("High", "Critical")]
    if not high_crit:
        return  # do nothing if no High/Critical

    sev = highest_severity(high_crit)
    subject = f"[ALERT] {sev} vulnerabilities detected on {scan_result['target']}"
    html_body = build_html_body(scan_result, high_crit)
    send_email(subject, html_body)

def highest_severity(findings):
    order = {"Critical": 4, "High": 3, "Medium": 2, "Low": 1, "Informational": 0}
    return max(findings, key=lambda f: order[f["severity"]])["severity"]

def build_html_body(scan_result, findings):
    rows = ""
    for f in findings:
        rows += f"""
        <tr>
          <td>{f['name']}</td>
          <td>{f['severity']}</td>
          <td>{f['score']}</td>
          <td>{f['recommended_action']}</td>
        </tr>
        """
    html = f"""
    <html>
    <body>
      <h2>Web Vulnerability Alert</h2>
      <p>Target URL: <strong>{scan_result['target']}</strong></p>
      <p>Scan Timestamp (UTC): {scan_result['timestamp']}</p>
      <p>Overall Risk Score: {scan_result['overall_score']}</p>

      <h3>High and Critical Findings</h3>
      <table border="1" cellpadding="5" cellspacing="0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Severity</th>
            <th>Score</th>
            <th>Recommended Action</th>
          </tr>
        </thead>
        <tbody>
          {rows}
        </tbody>
      </table>

      <hr>
      <p style="font-size: 12px; color: #666;">
        Disclaimer: This automated email is generated by a student assignment
        vulnerability scanner and is intended only for test/lab targets.
        Do not use this tool on live or unauthorized systems.
      </p>
    </body>
    </html>
    """
    return html

def send_email(subject, html_body):
    if DEMO_MODE:
        print("=== DEMO EMAIL ALERT ===")
        print(f"Subject: {subject}")
        print(f"From: {ALERT_FROM}")
        print(f"To: {ALERT_TO}")
        print("HTML Body:")
        print(html_body)
        print("=== END DEMO EMAIL ===")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = ALERT_FROM
    msg["To"] = ALERT_TO

    part = MIMEText(html_body, "html")
    msg.attach(part)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(ALERT_FROM, [ALERT_TO], msg.as_string())
        print("Email alert sent successfully!")
    except Exception as e:
        # For assignment, we just avoid crashing if email fails
        print("Email send failed:", e)
